stages:
  - build
  - lint
  - test
  - deploy

variables:
  DOCKER_IMAGE_NAME: "myserver"
  CI_REGISTRY_IMAGE: "counter-image"
  GTEST_DIR: "./googletest"

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_NAME .

lint:
  stage: lint
  image: docker.io/cppcheck/cppcheck:latest # use image to check cpp code!
  script:
    - cppcheck --enable=all --error-exitcode=1 myserver.cpp

test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y cmake g++
    - mkdir build
    - cd build
    - cmake $GTEST_DIR
    - make
    - cd ..
    - g++ -o mytests test_myserver.cpp -lgtest -lgtest_main -pthread
    - ./mytests

deploy_dev:
  stage: deploy
  script:
    - docker tag $DOCKER_IMAGE_NAME $CI_REGISTRY_IMAGE:develop
    - docker push $CI_REGISTRY_IMAGE:develop
  only:
    - develop # trigger for develop branch

deploy_prod:
  stage: deploy
  script:
    - docker tag $DOCKER_IMAGE_NAME $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master  # trigger only for master branch