stages:
  - build
  - lint
  - test
  - deploy

variables:
  DOCKER_IMAGE_NAME: "myserver"
  CI_REGISTRY_IMAGE: ""

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_NAME .

lint:
  stage: lint
  image: node:latest
  script:
    - npm install
    - npx eslint .

test:
  stage: test
  script:
    - test-command-here

deploy_dev:
  stage: deploy
  script:
    - docker tag $DOCKER_IMAGE_NAME $CI_REGISTRY_IMAGE:develop
    - docker push $CI_REGISTRY_IMAGE:develop

deploy_prod:
  stage: deploy
  script:
    - docker tag $DOCKER_IMAGE_NAME $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - develop
    - master  # trigger only for master and develop branch